config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource_id_regex  = /[a-zA-Z0-9\.%#\$&\?\(\)\=\+\-\_\:\\]+/
  uuid_regex         = /[a-zA-Z0-9\-]+/
  res_options        = { id: resource_id_regex }
  uuid_options       = { id: uuid_regex }
  root to: "feeds#index"

  resources :user_sessions, only: [:create]
  get  "login",  to: "user_sessions#new"    , as: :login
  post "logout", to: "user_sessions#destroy", as: :logout
  get "/auth/:provider/callback", to: "authentications#callback"
  resources :users do
    resources :entries, only: [:index], constraints: res_options
    resources :preferences, except: [:show]
  end
  resources :authentications, only: [:destroy]
  resources :entries do
    get "feedly", action: :show_feedly, on: :member
    get "crawl" , action: :crawl      , on: :member
    resources :tracks   , controller: :enclosures, type: "Track"   , only: :index
    resources :albums   , controller: :enclosures, type: "Album"   , only: :index
    resources :playlists, controller: :enclosures, type: "Playlist", only: :index

    resources :tracks   , controller: :entry_enclosures, type: "Track"   , only: %i[new create destroy]
    resources :albums   , controller: :entry_enclosures, type: "Album"   , only: %i[new create destroy]
    resources :playlists, controller: :entry_enclosures, type: "Playlist", only: %i[new create destroy]

    post   "like"  , to: :like  , as: :likes
    delete "unlike", to: :unlike, as: :like
    post   "save"  , to: :save  , as: :saves
    delete "unsave", to: :unsave, as: :save
    post   "read"  , to: :read  , as: :reads
    delete "unread", to: :unread, as: :read
  end
  resources :entry_enclosures, only: %i[create edit update destroy]
  resources :read_entries , only: %i[create destroy]
  resources :feeds, constraints: res_options, shallow: true do
    get "feedly", action: :show_feedly, on: :member
    resources :entries, only: [:index], constraints: uuid_options
  end

  resources :topics do
    get "mix_issue", to: :mix_issue, as: :mix_issue
    resources :feeds, only: [:index]
  end
  resources :subscriptions, except: [:new]
  resources :categories do
    resources :subscriptions, only: [:index]
  end
  %i[tracks albums artists playlists].each do |res|
    resources res, controller: :enclosures, type: res.to_s.classify, except: %i[edit update] do
      post   "like"  , to: :like  , as: :likes
      delete "unlike", to: :unlike, as: :like
      post   "save"  , to: :save  , as: :saves
      delete "unsave", to: :unsave, as: :save
      post   "play"  , to: :play  , as: :plays
      get    "search", on: :collection
      post   "create_identity", on: :member if res != :playlists
      if res == :playlists
        member do
          get "crawl"
          get "activate"
          get "deactivate"
        end
        get "actives"   , on: :collection
      end
    end
  end

  %i[track_identities album_identities].each do |res|
    resources res, controller: :identities, type: res.to_s.classify do
      get "search", on: :collection
      member do
        get "crawl"
      end
    end
  end

  resources :artist_identities do
    get "search", on: :collection
    get "crawl", on: :member
  end

  resources :keywords do
    resources :entries, only: [:index]
  end
  resources :tags do
    resources :entries, only: [:index]
  end
  resources :walls do
    resources :resources, only: [:new]
  end
  resources :resources,  only: %i[create edit update destroy]
  resources :journals do
    resources :issues do
      post "daily", action: :create_daily, on: :collection
      post "collect_entries", action: :collect_entries, on: :member
    end
  end
  resources :issues, only: []  do
    resources :entry_issues, only: [:new]
    resources :entries     , only: [:index]

    resources :enclosure_issues, only: [:new]
    resources :tracks   , controller: :enclosures, type: "Track"   , only: :index
    resources :albums   , controller: :enclosures, type: "Album"   , only: :index
    resources :playlists, controller: :enclosures, type: "Playlist", only: :index
  end
  resources :entry_issues    , only: %i[create edit update destroy]
  resources :enclosure_issues, only: %i[create edit update destroy]

  resources :mixes, only: %i[index show], constraints: res_options do
    member do
      get ":enclosures" => "mixes/enclosures#show"
    end
  end

  scope :v3 do
    use_doorkeeper
  end

  namespace :spotify do
    resources :tokens, only: [] do
      collection do
        post "swap"   , action: :swap
        post "refresh", action: :refresh
      end
    end
  end

  namespace :v3 do
    resources :profile, controller: :users, only: %i[show update] do
      collection do
        get  ""   , to: "users#me"
        put  ""   , to: "users#create"
        post ""   , to: "users#update"
        get "edit", to: "users#edit"
      end
      member do
        delete ":provider", to: "authentications#destroy"
      end
    end

    resources :preferences, only: [:index] do
      post "", action: "update", on: :collection
    end

    post "/markers" => "markers#mark"

    resources :walls, only: [], constraints: res_options do
      member do
        get "", action: :show
      end
    end

    resources :streams, only: [], constraints: res_options do
      member do
        get "ids",      action: :show
        get "contents", action: :show

        get ":enclosures/ids"      => "streams/enclosures#show"
        get ":enclosures/contents" => "streams/enclosures#show"
      end
    end

    resources :mixes, only: [], constraints: res_options do
      member do
        get "ids",      action: :show
        get "contents", action: :show

        get ":enclosures/ids"      => "mixes/enclosures#show"
        get ":enclosures/contents" => "mixes/enclosures#show"
      end
    end

    resources :feeds, only: [:show], constraints: res_options do
      post ".mget", action: :list, on: :collection
    end
    get "/search/feeds"         => "feeds#search"

    resources :topics, only: %i[index destroy], constraints: res_options do
      post "", action: :update, on: :member
    end

    resources :entries, only: [:show], constraints: res_options do
      post ".mget", action: :list, on: :collection
    end

    resources :subscriptions, only: %i[index create destroy], constraints: res_options

    resources :categories, only: %i[index destroy], constraints: res_options do
      post "", action: :update, on: :member
    end

    resources :tracks, controller: :enclosures, type: "Track",
                       only: [:show], constraints: uuid_options do
      post ".mget", action: :list, on: :collection
      resources :playlists, only: [:index], controller: :enclosures, type: "Playlist"
    end

    resources :albums, controller: :enclosures, type: "Album",
                       only: [:show], constraints: uuid_options do
      post ".mget", action: :list, on: :collection
    end

    resources :artists, controller: :enclosures, type: "Artist",
                        only: [:show], constraints: uuid_options do
      post ".mget", action: :list, on: :collection
    end

    resources :playlists, controller: :enclosures, type: "Playlist",
                          only: [:show], constraints: uuid_options do
      post ".mget", action: :list, on: :collection
      resources :tracks, only: [:index], controller: :enclosures, type: "Track"
    end

    [TrackIdentity, AlbumIdentity, ArtistIdentity].each do |m|
      resources m.table_name.to_sym, controller: :enclosures, type: m.name do
        post ".mget", action: :list, on: :collection
      end
    end

    get "/artist/:slug" => "enclosures#show_by_slug", :type => "ArtistIdentity"

    resources :keywords, only: %i[index destroy], constraints: res_options do
      post "", action: :update, on: :member
    end

    resources :tags, only: [:index], constraints: res_options do
      id_list_regex = /[a-zA-Z0-9\.\,%#\$&\?\(\)\=\+\-\_\:\\]+/
      c             = { tag_ids: id_list_regex, entry_ids: id_list_regex }
      post "", action: :update, on: :member
      collection do
        put    ":tag_ids"           , action: :tag_entry    , constraints: c
        put    ":tag_ids/:entry_ids", action: :tag_entries  , constraints: c
        delete ":tag_ids/:entry_ids", action: :untag_entries, constraints: c
        delete ":tag_ids"           , action: :destroy      , constraints: c
      end
    end
  end
end

app/views/resources/_form.html.slim
= form_for @resource, url: @resource, html: { class: "form form-horizontal resource" } do |f|
  - if @resource.errors.any?
    #error_explanation
      h2 = "#{pluralize(@resource.errors.count, "error")} prohibited this wall from being saved:"
      ul
        - @resource.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.hidden_field :wall_id, value: @resource.wall_id
  .form-group
    = f.label 'resource id', :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :resource_id, :class => 'form-control'
    = f.error_span(:resource_id)
  .form-group
    = f.label :resource_type, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :resource_type, Resource.resource_types.keys.to_a, {}, class: 'form-control'
    = f.error_span(:resource_type)

  .form-group
    = f.label :engagement, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field :engagement, :class => 'form-control'
    = f.error_span(:engagement)
  .form-group
    = f.label :options, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.hidden_field :options, :class => 'form-control'
    = f.error_span(:options)

  div.row#stream_options
    span#period_label.control-label.col.col-lg-3 period
    '
    = select_tag 'period',  options_for_select(['', 'daily', 'weekly', 'monthly'])
    br
    br
    span#mix_type_label.control-label.col.col-lg-3 mix_type
    '
    = select_tag 'mix_type',  options_for_select(['hot', 'popular', 'featured'])
  div.row#custom_options_new
    br
    br
    span.control-label.col.col-lg-3 key
    '
    = text_field_tag 'key', '', id: 'option_key'
    '
    span value
    '
    = text_field_tag 'value', '', id: 'option_value'
    '
    button#option_add.btn.btn-default
      i.fas.fa-plus
  div.row#custom_options
  br
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), edit_wall_path(@wall), :class => 'btn'

javascript:
  var resourceType  = document.getElementById("resource_resource_type");
  var options       = document.getElementById("resource_options");
  var streamOptions = document.getElementById("stream_options");
  var optionAdd     = document.getElementById("option_add");

  var period       = document.getElementById("period");
  var mixType      = document.getElementById("mix_type");

  var periodLabel  = document.getElementById("period_label");
  var mixTypeLabel = document.getElementById("mix_type_label");

  var optionsValue = '{}';
  if (options && options.value.length > 0) {
    optionsValue = options.value
  }
  var values = JSON.parse(optionsValue);

  function updateTextFields() {
    switch (resourceType.value) {
      case 'stream':
      case 'track_stream':
      case 'album_stream':
      case 'playlist_stream':
        streamOptions.style.display = '';
        period.style.display        = '';
        periodLabel.style.display   = '';
        mixType.style.display       = 'none';
        mixTypeLabel.style.display  = 'none';
        if (period.value) {
          values.period = period.value;
        }
        delete values['type']
        break;
      case 'mix':
      case 'track_mix':
      case 'album_mix':
      case 'playlist_mix':
        streamOptions.style.display = '';
        period.style.display        = '';
        periodLabel.style.display   = '';
        mixType.style.display       = '';
        mixTypeLabel.style.display  = '';
        if (period.value) {
          values.period = period.value;
        }
        values.type = mixType.value;
        break;
      default:
        streamOptions.style.display = 'none';
        delete values['period']
        delete values['type']
        break;
    }
    options.value = JSON.stringify(values);
  }
  function updateOptionsValue() {
    options.value = JSON.stringify(values);
  }
  function addOption(key, value) {
    if (key === '') {
      return;
    }
    values[key] = value;
    updateOptionsValue();
    var $pair = $('<div />')
      .attr('data-key', key)
      .attr('data-value', value)
      .append(
        '<span class="resource-option-key control-label col col-lg-3">' +
          key +
        '</span>' +
        '<span class="resource-option-value control-label">' + value + '</span>' + ' ' +
        '<button class="resource-option-button btn btn-default">' +
          '<i class="fas fa-minus"/>' +
        '</button>'
      );
    $("#custom_options").append($pair);
  }
  resourceType.addEventListener('change', updateTextFields);
  period.addEventListener(      'change', updateTextFields);
  mixType.addEventListener(     'change', updateTextFields);
  optionAdd.addEventListener(    'click',   function(e) {
    e.preventDefault();
    var $key = $('#option_key');
    var $value = $('#option_value');
    addOption($key.val(), $value.val());
  });
  $('#custom_options').on('click', '.resource-option-button', function(e) {
    e.preventDefault();
    var $pair = $(e.target).closest('.resource-option-button').parent();
    var key = $pair.attr('data-key');
    delete values[key];
    $pair.remove();
    updateOptionsValue();
  });

  try {
    var v = options.value ? JSON.parse(options.value) : {};
    Object.keys(v).forEach(function(key) {
      if (key === 'period') {
        period.value  = v[key];
      } else if (key === 'type') {
        mixType.value = v[key];
      } else {
        addOption(key, v[key]);
      }
    });
  } finally {
    updateTextFields();
  }

app/views/resources/edit.html.slim
.page-header
  h1.title Edit item of Resource Collection
= render :partial => "form"

app/views/resources/new.html.slim
.page-header
  h1 New item of Resource Collection

== render 'form'